# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tABMJOOdgwo4OuHKO-Y7b7Vw1VBuqKVn
"""

import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

print("--- Installing System Libraries & Build Tools ---")
!apt-get update && apt-get install -y build-essential cmake make ffmpeg libsndfile1

print("\n--- Installing Python Packages ---")
!pip install --upgrade pip
!pip install "transformers[torch]" "datasets" "torchcodec<0.5" "pyctcdecode" "num2words" "librosa" "evaluate" "jiwer"


print("\n--- Compiling and Installing KenLM ---")
!pip install https://github.com/kpu/kenlm/archive/master.zip


import torch

print("\n=== SYSTEM GPU VERIFICATION ===")
if torch.cuda.is_available():

    device = torch.device("cuda")
    print(f"✓ Success! GPU is ACTIVE and available in this session.")
    print(f"  Device Name: {torch.cuda.get_device_name(0)}")


    dummy_x = torch.rand(1000, 1000, device=device)
    dummy_y = torch.matmul(dummy_x, dummy_x)
    print("✓ Successfully executed tensor math on GPU to trigger active state!")
else:
    device = torch.device("cpu")
    print("✗ WARNING: GPU is NOT active.")
    print("  Go to: 'Runtime' -> 'Change runtime type' -> Select 'T4 GPU' (or better).")

"""## Load and preprocess dataset"""

import torch
from datasets import load_dataset, Audio


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✓ Pipeline targeted to run on: {device.type.upper()}")

if device.type == "cuda":

    warmup_tensor = torch.zeros(1, device=device)
    print(f"  GPU Active: {torch.cuda.get_device_name(0)}")
else:
    print("  ⚠ Running on CPU. Performance will be slow.")


print("\n--- Loading FLEURS (German) Dataset ---")


dataset = load_dataset(
    "google/fleurs",
    "de_de",
    streaming=False,
    revision="refs/pr/31"
)

dataset = dataset.cast_column(
    "audio",
    Audio(decode=False)
)

print("\n✓ Dataset loaded successfully without streaming!")
print(dataset)

"""> Let's create a new column `processed_text` across all datasets by replacing numerals with text following the procedure given in the previous assignment (2). We do not perform umlaut correction as umlaut characters are supported by the model we are going to use here."""

import re
from num2words import num2words


def replace_number(match):
    token = match.group(0)

    # Ordinal (e.g. 3., 21., 100.)
    if token.endswith("."):
        value = int(token[:-1])
        return num2words(value, lang="de", to="ordinal")

    value = int(token)

    # Years between 1100 and 2050
    if 1100 < value < 2050:
        return num2words(value, lang="de", to="year")


    return num2words(value, lang="de")

re.sub(r"\d+\.|\d+", replace_number, "Ich wurde am 3. Mai 1985 geboren.")

import re
import torch


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == "cuda":
    _ = torch.zeros(100, 100, device=device)
    print(f"✓ GPU is actively engaged: {torch.cuda.get_device_name(0)}")
else:
    print("⚠ Running on CPU.")


def preprocess_text(example):
    example["processed_text"] = re.sub(r"\d+\.|\d+", replace_number, example["raw_transcription"])
    return example


dataset = dataset.map(preprocess_text)


print("\n✓ Preprocessing completed across all splits!")
print("Sample processed text:", dataset["train"][0]["processed_text"])

"""## Train a Language Model

Prepare corpus iterating through `dataset['train']` and save it to `corpus.txt` with one sentence per line, each sentence with space separated words.
"""

import re
import torch


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == "cuda":
    _ = torch.zeros(100, 100, device=device)
    print(f"✓ GPU is actively engaged: {torch.cuda.get_device_name(0)}")
else:
    print("⚠ Running on CPU.")


print("\n--- Writing train corpus to corpus.txt ---")

with open("corpus.txt", "w", encoding="utf-8") as f:
    for example in dataset["train"]:

        text = example["processed_text"]


        text = re.sub(r"[^\w\s\u00C0-\u00FF]", "", text)
        words = text.strip().split()


        space_separated_sentence = " ".join(words)


        if space_separated_sentence:
            f.write(space_separated_sentence + "\n")

print("✓ Done! corpus.txt created successfully.")
print("Sample line from file:")
with open("corpus.txt", "r", encoding="utf-8") as f:
    print(f.readline().strip())

"""- Install KenLM on your computer by following [https://github.com/kpu/kenlm](https://github.com/kpu/kenlm).
- Train a trigram language model on this corpus using the command
  > `lmplz --order 3 --discount_fallback --text corpus.txt --arpa lm.arpa --memory 10G`

## Compare WER using CTC with and without LM

Let's run `aware-ai/wav2vec2-base-german` on sample audio from `datasets['validation']` and see its output
"""

import torch
from IPython.display import Audio
import librosa
import io
from transformers import AutoProcessor, AutoModelForCTC


sample = dataset["validation"][0]

audio_bytes = sample["audio"]["bytes"]


waveform, sr = librosa.load(
    io.BytesIO(audio_bytes),
    sr=None,
    mono=True
)

Audio(waveform, rate=sr)

import torch
from transformers import AutoProcessor, AutoModelForCTC

processor = AutoProcessor.from_pretrained(
    "aware-ai/wav2vec2-base-german"
)

model = AutoModelForCTC.from_pretrained(
    "aware-ai/wav2vec2-base-german"
)

model.eval()

inputs = processor(
    waveform,
    sampling_rate=sr,
    return_tensors="pt",
    padding=True
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    logits = model(**inputs).logits

pred_ids = torch.argmax(logits, dim=-1)

prediction = processor.batch_decode(pred_ids)[0]

print("Reference:")
print(sample["processed_text"])

print("\nPrediction:")
print(prediction)

"""> Let's write an evaluator function that takes predictions and transcriptions to report word error rate (WER) and character error rate (CER)"""

import evaluate

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")


def evaluate_asr(predictions, references):
    """
    Parameters
    ----------
    predictions : list[str]
        ASR hypotheses
    references : list[str]
        Ground-truth transcriptions

    Returns
    -------
    dict
        {"WER": ..., "CER": ...}
    """
    wer = wer_metric.compute(
        predictions=predictions,
        references=references
    )

    cer = cer_metric.compute(
        predictions=predictions,
        references=references
    )

    return {
        "WER": wer,
        "CER": cer,
    }

"""

Let's run predictions on plain model (as in the example) and report WER and CER. Fill in the missing code"""

import io
import soundfile as sf
import librosa
import torch
from tqdm.auto import tqdm


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == "cuda":
    _ = torch.zeros(100, 100, device=device)
    print(f"✓ GPU is active: {torch.cuda.get_device_name(0)}")
else:
    print("⚠ Running on CPU. This evaluation loop will take a long time!")


model = model.to(device)
model.eval()

predictions = []
references = []


for sample in tqdm(dataset["test"]):


    audio_bytes = sample["audio"]["bytes"]


    raw_audio, original_sr = sf.read(io.BytesIO(audio_bytes))


    target_sr = 16000
    if original_sr != target_sr:
        waveform = librosa.resample(raw_audio, orig_sr=original_sr, target_sr=target_sr)
    else:
        waveform = raw_audio


    inputs = processor(
        waveform,
        sampling_rate=target_sr,
        return_tensors="pt",
        padding=True
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}


    with torch.no_grad():
        logits = model(**inputs).logits


    pred_ids = torch.argmax(logits, dim=-1)
    prediction = processor.batch_decode(pred_ids)[0]


    predictions.append(prediction)
    references.append(sample["processed_text"])


results = evaluate_asr(
    predictions,
    references
)

print(f"\n✓ Evaluation complete!")
print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")

from google.colab import files

print("Please select your local 'lm.arpa' file to upload:")
uploaded = files.upload()

for fn in uploaded.keys():
    print(f'✓ Successfully uploaded "{fn}" ({len(uploaded[fn])} bytes)')

"""> Now use the trained `lm.arpa` via the module `pyctcdecode` to improve decodings and report WER and CER on `dataset[test]`

- Given CTC probabilities $p_{ctc}$ on input features $X = x_1, \dots, x_T$ and n-gram language model probabilities $p_{lm}(w_i \mid w_{i-1}, \ldots, w_{i-n+1})$ on corresponding word sequence $W = w_1, \ldots, w_L$ and alignments $\mathcal{A}(W)$, the decoding maximizes:

> $\mathcal{L}_{ctc+lm} = \sum_{\pi \in \mathcal{A}(W)}p_{ctc}(\pi \mid X) + \alpha\sum_{i=n}^L\log p_{lm}(w_i \mid w_{i-1},\ldots, w_{i-n+1}) + \beta |W|$

- In other words, $\alpha$ weighs the language model while $\beta$ is word insertion bonus
"""

import io
import soundfile as sf
import librosa
import torch
from tqdm.auto import tqdm
from pyctcdecode import build_ctcdecoder


vocab = processor.tokenizer.get_vocab()

labels = [
    token
    for token, idx in sorted(vocab.items(), key=lambda x: x[1]) if token[0] != '{'
]


decoder = build_ctcdecoder(
    labels=labels,
    kenlm_model_path="lm (1).arpa",
    alpha=0.2,
    beta=0.8
)

print("✓ CTC Decoder with Language Model successfully built!")


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

lm_predictions = []
references = []

print("\n--- Running Evaluation with Language Model ---")
for sample in tqdm(dataset["test"]):


    audio_bytes = sample["audio"]["bytes"]
    raw_audio, original_sr = sf.read(io.BytesIO(audio_bytes))


    target_sr = 16000
    if original_sr != target_sr:
        waveform = librosa.resample(raw_audio, orig_sr=original_sr, target_sr=target_sr)
    else:
        waveform = raw_audio


    inputs = processor(
        waveform,
        sampling_rate=target_sr,
        return_tensors="pt",
        padding=True
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}


    with torch.no_grad():
        logits = model(**inputs).logits


    logits_numpy = logits[0].cpu().numpy()


    prediction = decoder.decode(logits_numpy)


    lm_predictions.append(prediction)
    references.append(sample["processed_text"])


results = evaluate_asr(
    lm_predictions,
    references
)

print(f"\n✓ Evaluation with LM complete!")
print(f"WER (with LM): {results['WER']:.4f}")
print(f"CER (with LM): {results['CER']:.4f}")

sample = dataset["validation"][0]

waveform, sr = librosa.load(
    io.BytesIO(sample["audio"]["bytes"]),
    sr=None,
    mono=True
)

inputs = processor(
    waveform,
    sampling_rate=sr,
    return_tensors="pt"
).to(device)

with torch.no_grad():
    logits = model(**inputs).logits

# Greedy decoding
pred_ids = torch.argmax(logits, dim=-1)

greedy_text = processor.batch_decode(
    pred_ids,
    skip_special_tokens=True
)[0]

# LM decoding
logits_np = logits[0].cpu().numpy()

lm_text = decoder.decode(logits_np, beam_width=100)

print("REFERENCE:")
print(sample["processed_text"])

print("\nGREEDY:")
print(greedy_text)

print("\nKENLM:")
print(lm_text)

"""### Q5

Write the code for evaluating CTC + LM decoding using `beam_width = 100` and report WER and CER. What are your observations?
"""

import io
import soundfile as sf
import librosa
import torch
from tqdm.auto import tqdm

predictions = []
references = []


model = model.to(device)
model.eval()

print("--- Running Evaluation with Language Model (Beam Width = 100) ---")
for sample in tqdm(dataset["test"]):


    audio_bytes = sample["audio"]["bytes"]
    raw_audio, original_sr = sf.read(io.BytesIO(audio_bytes))


    target_sr = 16000
    if original_sr != target_sr:
        waveform = librosa.resample(raw_audio, orig_sr=original_sr, target_sr=target_sr)
    else:
        waveform = raw_audio


    inputs = processor(
        waveform,
        sampling_rate=target_sr,
        return_tensors="pt",
        padding=True
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}


    with torch.no_grad():
        logits = model(**inputs).logits


    logits_numpy = logits[0].cpu().numpy()
    prediction = decoder.decode(logits_numpy, beam_width=100)


    predictions.append(prediction)
    references.append(sample["processed_text"])


results = evaluate_asr(
    predictions,
    references
)

print(f"\n✓ Evaluation complete!")
print(f"WER: {results['WER']:.4f}")
print(f"CER: {results['CER']:.4f}")
